/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iving_myjniapplication_JNIStub */

#ifndef _Included_com_iving_myjniapplication_JNIStub
#define _Included_com_iving_myjniapplication_JNIStub
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iving_myjniapplication_JNIStub
 * Method:    getDataFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_iving_myjniapplication_JNIStub_getDataFromJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
